### ISSUE TITLE
get-config from a pis2t return no data

### ISSUE THREAD

**Issue by helijia21** [nokia/atom-netconf#10]
# send
`<rpc message-id="100" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<get-config>
       <source>
              <running/>
    </source>
       <filter type="subtree">
              <terminal-device xmlns="http://openconfig.net/yang/terminal-device">
              </terminal-device>
       </filter>
</get-config>
</rpc>`

# return
`<rpc-reply message-id="100"
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<data>
</data>
</rpc-reply>`

**Comment by wisotzky** [comment]
Looks like the response is received, but without data. Seems more related to you pis2t device (whatever this is). Have you tried to run without the subtree filter? Just guessing the filter does not have any matches.

**Comment by helijia21** [comment]
it'ok when i use your atom-netconf to test the psi2t  , while i use python and paramiko to send this xml , the return shows that no data...

**Comment by helijia21** [comment]
i also read about your another project on the github  --> nokia/ncctools  .Seens that the ncclient is incompatible  withi pss/psi. I have to write a dircet client for the nokia devices, but cannot recv the data from the rpc reply message

**Comment by wisotzky** [comment]
@helijia21, doing a bit of cleanup on this project. Was there any progress on this item you've mentioned 2 years ago?
If there is nothing to be done around this ATOM plugin, I would rather close this issue...

**Comment by wisotzky** [comment]
@helijia21, did you fixed your issues on pss/psi?

Be aware, that we've moved from ATOM.io to Visual Studio Code.
Details can be found in the README of this project.

No plans for changes on atom-netconf as ATOM.io is now in sunset mode.
