### ISSUE TITLE
atom-netconf does not work with the latest version of Atom (1.56)

### ISSUE THREAD

**Issue by andre-d-brizido-alb** [nokia/atom-netconf#12]
With atom version 1.56 the following error occurs:
![error](https://user-images.githubusercontent.com/14160800/115241709-09774d80-a119-11eb-8f31-bc65249cdaed.png)

I if revert to version 1.55 the plugin works again.

**Comment by nscarlettwolf** [comment]
I see the same problem with Atom 1.56 and atom-netconf version 3.2.0.  If I revert to Atom 1.55, the plugin loads and works fine.

**Comment by wisotzky** [comment]
Fixed by:
https://github.com/nokia/atom-netconf/commit/53bd8c3fec2cd3dd0a01c3480cd6a8d157a012dc#diff-76b5a357391276b282a516f54f48ef3c207f46d8192dc58c208d5183d38415f8
