### ISSUE TITLE
netconf supervision failure after 70sec

### ISSUE THREAD

**Issue by potpara** [nokia/atom-netconf#13]
Why NETCONF supervision fails always after 70sec (notification timer 60sec, guard timer 10sec)? It looks like NETCONF client is not restarting watchdog timer on NETCONF server. 
Is there any way to trace NETCONF on Atom, or at least to capture debug logs? tcpdump doesn't help cause NETCONF uses SSH and data is encrypted.

**Comment by wisotzky** [comment]
What kind of device are you using?

To enable logging:
1) **View > Developer > Toggle Dev Tools**
2) Go to package settings and enable as needed "Netconf Module" and "SSH Module"

Alternatively check my ncproxy tool from GitHub. That is some sort of "man-in-the-middle" tool, that traces all server and client messages. Also it allows you to patch messages for try-if scenarios.

**Comment by wisotzky** [comment]
For ncproxy go here:
https://github.com/nokia/nctools

**Comment by potpara** [comment]
Hi,
thanks for your quick response. It is sort of radio transmitter.

**Comment by wisotzky** [comment]
@potpara, let me know if debugging works for you. If there is an issue on our module, please let me know. However, I doubt it is the case.

**Comment by potpara** [comment]
Hi wisotzky,
i failed to find useful info in Atom debug. However I succeeded to tail -f netconf log on device itself. Device enters reboot after supervision timer (70sec) expired cause Atom Netconf do not attempt to subscribe for supervision notifications, and doesn't attempt to restart supervision watchdog timer on device. Netconf client and server just exchanges two capability hello msg and that's all.
2021/03/14 19:14:47 M-Plane conectivity monitoring: START supervision on session-id(3).
Mar 14 19:14:46 local4.info netopeer2-server[7968]: Session 3: sending message (len=2796):
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability>
    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&amp;revision=2016-08-05</capability>
    <capability>urn:ietf:params:xml:ns:yang:1?module=yang&amp;revision=2017-02-20</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:netconf:capability:yang-library:1.0?revision=2019-01-04&amp;module-set-id=54</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2018-02-14</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-06-01&amp;features=writable-running,startup,url,xpath</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2012-02-06</capability>
    <capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&amp;revision=2014-12-10</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2011-06-01</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
    <capability>urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&amp;revision=2014-08-06</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-system?module=ietf-system&amp;revision=2014-08-06&amp;features=authentication,local-users</capability>
    <capability>urn:ietf:params:xml:ns:yang:iana-if-type?module=iana-if-type&amp;revision=2017-01-19</capability>
  </capabilities>
  <session-id>3</session-id>
</hello>
Mar 14 19:14:46 local4.info netopeer2-server[7968]: Session 3: message (len=2802) flushed successfully.
Mar 14 19:14:46 local4.info netopeer2-server[7968]: Session 3: received message (len=262):
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
  </capabilities>
</hello>
2021/03/14 19:15:57 M-Plane conectivity monitoring: OCCUR supervision failure on session-id(3).
2021/03/14 19:15:57 M-Plane conectivity monitoring: STOP supervision on session-id(3).

**Comment by wisotzky** [comment]
Hi @potpara
ATOM-NETCONF is able to subscribe (and receive) netconf event notifications.
Try it out and let me know.
Sven

**Comment by potpara** [comment]
I see. Some help would be great if possible. Do I need to send some rpc for supervision subscription? Can't find it package settings.

**Comment by wisotzky** [comment]
You need to craft the subscription rpc yourself.
Once done, system will start receiving notifications.

To see, what was received there is a dedicated icon in the status bar, that has the number of events received in the buffer. Once you click on this icon, the buffer is copied into a new text-window and cleared afterwards.

**Comment by potpara** [comment]
Great. Thanks a lot! I'll do that.

**Comment by potpara** [comment]
Hi Wisotzky,

well I did some analysis on this topic. By the way, reference yang model is o-ran-supervision.yang. Idea is to keep constant supervision over time on link between Netconf server and client. In case that supervision fails, Netconf server goes into reboot. After subscription Netconf server send notification, and after client receives it it replies with watchdog timer restart.
![image](https://user-images.githubusercontent.com/82977103/115927443-bab51500-a484-11eb-8658-ae927687017d.png)
From netconf log I can see that server send rpc-notification but client doesn't reply with rpc-supervision-watchdong reset.  Question: does Atom Netconf support automatic watchdog reset reply upon receiving notification? Attached is entire log.
[watchdogreset_missing.txt](https://github.com/nokia/atom-netconf/files/6368035/watchdogreset_missing.txt)

**Comment by wisotzky** [comment]
Hi @potpara,
Looks like interesting stuff. The **supervision-watchdog-reset** is not a common NETCONF thing, rather it looks coming from O-RAN. Therefore it is currently not implemented... However, you could send this rpc manually though (not sure how much time one would have aka what's the timeout). It might be an interesting question to implement an automatism here - aka auto respond.
I've got something fair similar on ncproxy. But this is only auto-responding to client messages but not server messages. So I feel from your comments, it might be worth in adding this. Let me think about it. At least for testing this would be a reasonable approach, however you would always need to go view proxy not doing this stuff direct.

**Comment by potpara** [comment]
Sorry @wisotzky , might be that my initial question wasn't formulated clearly. True, this is topic from O-RAN field, way to keep alive Netconf session between client and server (supervision). Server send Netconf notification each 60sec, and client has to auto-reply with watchdog reset, if there is no reply within 10sec server announce that supervision failed and goes into reboot. Actually my question was: if some kind of automatism is already implemented in Atom Netconf package, but now I understand that at current stage is not. However I can send rpc to reset watchdog timer manually and it works, but this is not suitable in some real environment.
![image](https://user-images.githubusercontent.com/82977103/115958809-47a1b200-a509-11eb-97f6-a872e5913952.png)

Thanks anyway for your time and efforts!
