### ISSUE TITLE
crash with <rpc-reply> containing umlaut 

### ISSUE THREAD

**Issue by berstrob** [nokia/atom-netconf#15]
Hi,
so if i try to <get> a reply that has something like an äöü in a value-string atom does kill the connection with : 
```
base_1_1 error

chunk start not found
ssh error

Error: base_1_1 error: chunk start not found
```

If i disable the 1.1 support it works.
Also setting the value does work with both modes . I am assuming it has something todo with the fact that those umlaut do count as "two chars" for the counting , at least it does with my netconf-server. 

Regards Bernd

**Comment by wisotzky** [comment]
Good catch... I was able to reproduce this issue by using Deutsche Umlaute (UTF-8). To fix it, multiple pieces need to be touched. Currently the receiver builds an UTF-8 compliant string from the chunks received over the underlying SSH connection. From here, it is using length/substring follow-up operations - which actually is based on characters not on octets.  Need some investigation to check, what needs to be changed to get this fixed.

**Comment by wisotzky** [comment]
I've added proper UTF8 handling in 3.4.1... Please update your system to cross-check if the correction works for you. I've tested against Nokia SR OS devices and it is doing the job for me.

Viel Spaß!

**Comment by berstrob** [comment]
Hi, 
thanks for the quick reply and work.
The good news firsts it does not crash anymore and setting does still work the same as it did before,  
but reading back now does print something like :
 `  <value>test Ã¤ Ã¶ Ã¼</value>` for `test ä ö ü`
 in 1.1 and in 1.0 mode , not sure how that happens. 
(i am testing against a netopeer2/sysrepo implementation)

Grüße :)

**Comment by wisotzky** [comment]
Sounds merkwürdig. Looks like in your case it shows unicode multi-byte char. Nokia SROS is quite restrictive the char-set for values, so I've tried it by setting the request-id accordingly which is supposed to be transparent. This actually was working fine. Let me look deeper if I find something.

**Comment by wisotzky** [comment]
Could you please try version 3.5.0?
I hope this should fix it for you.

Bitte bestätigen, ob es funktioniert!

**Comment by wisotzky** [comment]
@berstrob, could you please try out the latest version so I can finally close this item?

**Comment by berstrob** [comment]
Hi sorry,  
was already enjoying the long weekend Friday evening (had Monday off ), so did not check my mails till now. 
But it works now perfectly. 
Thank you very much!
