### ISSUE TITLE
ssh error

### ISSUE THREAD

**Issue by Chao-C-G** [nokia/atom-netconf#17]
Dear expert,

Atom reported ssh error:Error: Handshake failed: no matching key exchange algorithm, how can I solve it?
Thanks

**Comment by wisotzky** [comment]
Big @BigSonic, this is typically related to the version of the underlying ssh2 library. Please note, that we've followed the sunset of ATOM.io with our plugin and have now moved to Visual Studio Code. Check the README for details. The Visual Studio Code extension is prebuilt with the latest version of the underlying ssh2 library. If you find missing algorithms, please check if you can configure your network device to support something that is supported by the ssh2 library. Beside, you may consider to raise an issue against the ssh2 lib.
