### ISSUE TITLE
Post atom installation and Pulsar compatibility

### ISSUE THREAD

**Issue by Aloumvrios** [nokia/atom-netconf#18]
Since atom is no longer maintained and it's package manager is not working, what is the suggested way to install atom-netconf package?
Also, is the package working for Pulsar editor ( atom fork) ?

**Comment by wisotzky** [comment]
Hi @Aloumvrios, I am aware about the struggles on ATOM. It's possible to add the plugin manually into ATOM - but it's a bit of burden.

To have reasonable NETCONF solution for the wider community, I've started now to do a similar plugin for Visual Studio Code (vsCode). The current progress is good, however we won't get to the same level of usability. But performance-wise the new solution will become very attractive.

Most of the people I am working with have moved to vsCode or planning to move (from Atom, Sublime, IntelliJ, Eclipse, ...) - so I assume that having a plugin for vsCode is considered a reasonable step forward.

**Comment by wisotzky** [comment]
We've added support now for Visual Studio Code. Please check the README of this project for more details. There is currently no plan to support other editors like Pulsar. Please install VSCODE plus our new extension and let us know about your feedback!
