### ISSUE TITLE
Pretty XML function encodes the XML entities used inside CDATA Section.

### ISSUE THREAD

**Issue by kaja-mohideen** [nokia/atom-netconf#5]
Atom 1.20.1 on Ubuntu 16.04

![image](https://user-images.githubusercontent.com/5323964/31021441-760bc590-a553-11e7-8051-8a70931ffc6c.png)

![image](https://user-images.githubusercontent.com/5323964/31021454-7f3ec482-a553-11e7-805e-b0b4a42fccc9.png)

**Comment by wisotzky** [comment]
The reason is, that I am using the following XSLT to prettify:
```
<?xml version="1.0" encoding="UTF-8"?>
  <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="xml" version="1.0" encoding="utf-8" omit-xml-declaration="no" indent="yes"/>
    <xsl:strip-space elements="*"/>
    <xsl:template match="/">
      <xsl:copy-of select="."/>
    </xsl:template>
  </xsl:stylesheet>
```

Patching the XSLT to fit your example does provide the expected result:
`<xsl:output method="xml" version="1.0" encoding="utf-8" omit-xml-declaration="no" indent="yes" cdata-section-elements="NotOKToBeEncoded"/>`

Challenge in here is, that I need to know the name(s) of the attributes to use CDATA encoding. This makes it difficult to make the solution generic...

Any ideas?

**Comment by kaja-mohideen** [comment]
Ah!. XSLT.

Then we'll have to parse the XML to know which elements carry CDATA to _generate_ XSLT before transforming.

Challenge here, I think, is - CDATA is for parsers themselves. DOMParser may not give this information. Don't know how to do this !

**Comment by wisotzky** [comment]
@kaja-mohideen 
Have not yet seen NETCONF devices making use of CDATA elements. Have you? And if the answer is "yes", please provide me with the details!

I have seen discussion to auto-generating the XSLT used to pretify, but I am not sure if such solution would be universal. Reason is, that the `cdata-section-elements` only reference the element-name but not the exact position in the XML document. So it might be, that the source document contains the elements with the same name, sometimes using CDATA encoding and sometimes not. I don't really see, how to fix that.

So potentially the solution is, to provide my own CoffeeScript parsing/reformating function, which takes care about CDATA preservation. But this sounds like quite a bit of an effort - and unclear if it is worth. If you have a coding exmample which is proven to work, I can clearly integrate this into my tool.

**Comment by kaja-mohideen** [comment]
Hmm.. This is not really an XML (edit-config request) for NC usage. I just used the prettify function on my other XML as the feature is available in my atom.

Maybe, this part has to be extracted and put in xml plugin of atom - which may have more sophisticated functions already available (not sure though).

**Comment by wisotzky** [comment]
Hi @kaja-mohideen,
please check our latest work on Visual Studio Code... I am not planning changes on atom-netconf due to the sunset of ATOM. Details are available on README.
